name: MVP Build
description: Start a long-horizon autonomous agent build
title: "[MVP] Canopy Build"
labels: ["mvp", "long-horizon", "needs-approval"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Long-Horizon Agent Build

        **For Booth Staff:** This kicks off the autonomous agent to build the Canopy app.

        ### How it works
        1. Create this issue (just click "Create" below)
        2. Add a 🚀 reaction to approve it
        3. The agent automatically starts building using `prompts/canopy/BUILD_PLAN.md`
        4. Progress updates and screenshots will be posted to this issue
        5. Code is committed to the `agent-runtime` branch

        ### Architecture details
        - **Specification:** The agent reads from `prompts/canopy/BUILD_PLAN.md` (hardcoded)
        - **Issue queue:** Approved issues are synced to `human_backlog.json` on EFS
        - **Polling:** The agent pulls from `human_backlog.json` to find the next issue to work on
        - **Branch:** All work is committed to the `agent-runtime` branch
        - **Single runtime:** Only ONE agent runs at a time - additional issues are queued automatically

        **You don't need to provide any additional details** - the full specification is already in the repo.

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any special instructions or context for this build run
      placeholder: "Optional - leave blank for standard build"
    validations:
      required: false
